FROM node:alpine as builder

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

FROM node:alpine    

RUN npm -g install serve

WORKDIR /usr/src/app

COPY --from=builder /app/build .

EXPOSE 80

CMD ["serve", "-p", "80", "-s", "."]